config/routes.rb
require 'resque/server'

StoreEngine::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  resources :discounts, only: [:show]
  root to: 'stores#index'

  get "/code" => redirect("https://github.com/bradpsheehan/daughter_of_store_engine")
  put "/i18n" => "i18n#update"

  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  resources :sessions, only: [ :create ]

  get "/users/new" => "users#new", as: :signup
  resources :users, only: [ :create, :update ]

  get "/profile" => "users#show", as: :profile

  scope path: "account", as: "account" do
    get "/orders" => "orders#index", as: :orders
  end

  get "/orders/:guid" => "orders#show", as: :order

  resources :stores, only: [ :new, :create ]

  namespace :uber do
    resources :stores, only: [ :index ] do
      member do
        put :approve
        put :decline
        put :toggle_online_status
      end
    end
  end

  scope "/:store_path", as: :store do
    get "/" => "products#index", as: :home

    get "/checkout" => "checkouts#show", as: :checkout
    post "/checkout" => "checkouts#create", as: :checkout
    post "/buy_now" => "checkouts#buy_now", as: :buy_now

    resources :products, only: [ :show ]

    resource :cart, only: [ :update, :show, :destroy ] do
      member do
        put :remove_item
      end
    end

    get '/stock/products' => "admin/products#index", as: :stock_products
    get '/stock/products/:id/edit' => "admin/products#edit", as: :stock_edit_product

    namespace :admin do
      get '/' => "dashboards#manage", as: :manage

      get '/edit' => "dashboards#edit", as: :edit_store
      put '/update' => "dashboards#update", as: :update_store

      post '/role' => "roles#create", as: :create_role
      delete '/role' => "roles#destroy", as: :revoke_role

      get :dashboard, to: "orders#index", as: :dashboard

      resources :products do
        member do
          post :toggle_status
        end
      end
      resources :orders, only: [ :show, :update ]
      resources :order_items, only: [ :update, :destroy]
      resources :categories
      resources :discounts
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :status, :user_id, :store_id, :total
  belongs_to :user
  belongs_to :store
  has_many :order_items, validate: true, dependent: :destroy
  has_many :products, through: :order_items
  has_one :billing_address, as: :addressable
  has_one :shipping_address, as: :addressable

  before_validation :generate_guid, on: :create

  validates :user_id, presence: true
  validates :guid, presence: true
  validates :status, presence: true,
                    inclusion: {in: %w(pending cancelled paid shipped returned),
                                  message: "%{value} is not a valid status" }

  def to_param
    guid
  end

  def savings
    original_value - promo_value
  end

  def original_value
    order_items.inject(0) do |memo, order_item|
      memo += order_item.product.price
      memo
    end
  end

  def promo_value
    unless find_product_promotion.class == BigDecimal
      find_product_promotion.inject(0) do |memo, price|
        memo += price
        memo
      end
    else
      find_product_promotion.truncate
    end
  end

  def find_product_promotion
    promos = order_items.inject([]) do |memo, order_item|
      memo << order_item.product.promo_price
      memo
    end
    originals = order_items.inject([]) do |memo, order_item|
      memo << order_item.product.price
      memo
    end
    if promos == originals
      return []
    else
      return promos
    end
  end

  def self.by_status(status)
    if status.present? && status != 'all'
      order.where(status: status)
    else
      scoped
    end
  end

  def self.create_pending_order(user, cart_items, discount)
    transaction do
      create(status: 'pending', user_id: user.id).tap do |order|

        # cart_items converting into an order

        cart_items.each do |cart_item|
          order.order_items.build(product_id: cart_item.product.id,
                                  unit_price: cart_item.unit_price,
                                  quantity: cart_item.quantity)
        end

        subtotal = Hash.new(0)
        order.order_items.each do |item|
          subtotal[:amount] += item.unit_price * item.quantity
        end

        # TODO: to make this work you need a new column
        # order.amount_of_savings = discount.discount_amount * 100

        # Set the total amount to the current subtotal
        order.total = subtotal[:amount]
        # Update the total amount with any discount amounts
        # Store the total amount in the database in pennies
        order.total = discount.apply(order) * 100
        order.save!

      end
    end
  end

  # HACK: This is so we can use cart calculator
  def pretotal
    total
  end

  # Convert database dollar value stored in pennies to dollars and cents
  def total_in_dollars_and_cents
    total.to_f / 100
  end

  def update_status
    next_status = { 'pending' => 'cancelled',
                    'paid' => 'shipped',
                    'shipped' => 'returned' }
    self.status = next_status[self.status]
    self.save
  end

#this is where we need to apply the discount
  # def total
  #   if order_items.present?
  #     order_items.map {|order_item| order_item.subtotal }.inject(&:+)
  #   elsif order_items.present? && session[:discount]
  #     order_items.map {|order_item| order_item.subtotal }.inject(&:+) - session[:discount ]
  #   end
  # end

  private

  def generate_guid
    self.guid = SecureRandom.uuid
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :require_admin

  def index
    @count = current_store.orders.count
    @orders = current_store.orders.by_status(params[:status]).all
    @statuses = current_store.orders.count(group: :status)
    @active_tab = params[:status] || 'all'
  end

  def show
    @order = current_store.orders.find(params[:id])
  end

  def update
    @order = current_store.orders.find(params[:id])
    if params[:update_status]
      @order.update_status
    end
    redirect_to(:back)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :require_login, only: [:index ]

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find_by_guid!(params[:guid])
    @order_items = @order.order_items
    @order_savings = flash[:post_order_discount]
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def next_status(current_status)
    { 'pending' => t('order.status.next.pending'),
      'paid' => t('order.status.next.paid'),
      'shipped' => t('order.status.next.shipped')}[current_status]
  end

  def status_count(status)
    count = @statuses[status] || 0
    "#{count} #{t('order.status.' + status)}"
  end
end

app/views/admin/orders/_admin_dashboard_nav.html.haml
%ul.nav.nav-pills
  - if active_tab == 'all'
    %li.active
  - else
    %li
  = link_to "#{count} #{t 'total'}", store_admin_dashboard_path(current_store)
  - %w(pending cancelled paid shipped returned).each do |status|
    - if active_tab == status
      %li.active
    - else
      %li
    = link_to status_count(status), store_admin_dashboard_path(current_store, status: status)

app/views/admin/orders/_next_status_button.html.haml
- if next_status(order.status)
  = button_to next_status(order.status),                               |
    store_admin_order_path(current_store, order.id, update_status: true), |
    method: :put, class: 'btn btn-small'                               |

app/views/admin/orders/_order.html.haml
%tr
  %td= link_to "#{t('order.self')} ##{order.id}", store_admin_order_path(current_store, order.id)
  %td= order.created_at.to_s(:short)
  %td= order.status
  %td
    = render partial: 'next_status_button', locals: { order: order }

app/views/admin/orders/_order_item.html.haml
%tr
  %td= link_to order_item.product.title, store_product_path(@store.path, order_item.product_id)
  - if @order.status == 'pending' || @order.status == 'paid'
    %td
      = simple_form_for :admin_order_item, url: "/#{@store.path}/admin/order_items/#{order_item.id}", method: :put do |f|
        = f.hidden_field :order_item_id, value: order_item.id
        = f.input_field :quantity, value: order_item.quantity, class: 'span1'
        = f.button :submit, t('crud.update'), class: 'btn-mini'
      = button_to t('crud.delete'), store_admin_order_item_path(order_item), method: :delete, class: 'btn btn-mini btn-danger'
  - else
    %td= order_item.quantity
  %td= number_to_currency(order_item.unit_price)
  %td= number_to_currency(order_item.subtotal)

app/views/admin/orders/index.html.haml
.admin-order-index
  = render partial: 'shared/admin_navigation', locals: { active: :dashboard }
  .span8
    %h1= t 'admin.dashboard'
    %hr/
    - if @count > 0
      = render partial: 'admin_dashboard_nav', |
        locals: { active_tab: @active_tab,     |
        count: @count,                         |
        statuses: @statuses}                   |
      %br/
      %table.table
        %thead
      %th #
      %th= t 'model.createdat'
      %th= t 'model.status'
      %th= t 'model.modify'
      %tbody
        = render @orders
    - else
      = t 'order.none'

app/views/admin/orders/show.html.haml
.admin-order-show
  = render partial: 'shared/admin_navigation', locals: { active: false }
  .span8
    %h1
      = t 'order.self'
      \##{@order.id}
    %span.label.default= @order.status
    = render partial: 'next_status_button', locals: { order: @order }
    %hr/
    %p
      = t 'model.createdat'
      \: #{@order.created_at.to_s(:short)}
    %p
      = t 'model.updatedat'
      \: #{@order.updated_at.to_s(:short)}
    %p
      = t 'order.purchasername'
      \: #{@order.user.full_name}
    %p
      = t 'order.purchaseremail'
      \: #{@order.user.email}
    %h2
      = t 'product.collection'
    %table.table
      %thead
        %th= t 'product.title'
        %th= t 'product.quantity'
        %th= t 'product.unitprice'
        %th= t 'product.subtotal'
      %tbody
        = render partial: 'order_item', collection: @order.order_items
      %tfoot
        %tr
          %td
          %td
          %td{:style => "text-align: right;"}= t 'total'
          %td= number_to_currency(@order.total)