config/routes.rb
require 'resque/server'

StoreEngine::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  resources :discounts, only: [:show]
  root to: 'stores#index'

  get "/code" => redirect("https://github.com/bradpsheehan/daughter_of_store_engine")
  put "/i18n" => "i18n#update"

  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  resources :sessions, only: [ :create ]

  get "/users/new" => "users#new", as: :signup
  resources :users, only: [ :create, :update ]

  get "/profile" => "users#show", as: :profile

  scope path: "account", as: "account" do
    get "/orders" => "orders#index", as: :orders
  end

  get "/orders/:guid" => "orders#show", as: :order

  resources :stores, only: [ :new, :create ]

  namespace :uber do
    resources :stores, only: [ :index ] do
      member do
        put :approve
        put :decline
        put :toggle_online_status
      end
    end
  end

  scope "/:store_path", as: :store do
    get "/" => "products#index", as: :home

    get "/checkout" => "checkouts#show", as: :checkout
    post "/checkout" => "checkouts#create", as: :checkout
    post "/buy_now" => "checkouts#buy_now", as: :buy_now

    resources :products, only: [ :show ]

    resource :cart, only: [ :update, :show, :destroy ] do
      member do
        put :remove_item
      end
    end

    get '/stock/products' => "admin/products#index", as: :stock_products
    get '/stock/products/:id/edit' => "admin/products#edit", as: :stock_edit_product

    namespace :admin do
      get '/' => "dashboards#manage", as: :manage

      get '/edit' => "dashboards#edit", as: :edit_store
      put '/update' => "dashboards#update", as: :update_store

      post '/role' => "roles#create", as: :create_role
      delete '/role' => "roles#destroy", as: :revoke_role

      get :dashboard, to: "orders#index", as: :dashboard

      resources :products do
        member do
          post :toggle_status
        end
      end
      resources :orders, only: [ :show, :update ]
      resources :order_items, only: [ :update, :destroy]
      resources :categories
      resources :discounts
    end
  end
end

app/views/shared/_admin_navigation.html.haml
.span3
  %ul.nav.nav-list
    - if current_store.is_admin?(current_user)
      %li.nav-header= t('admin.self')
      %li{:class => active == :manage ? 'active' : ''}
        = link_to 'Manage', store_admin_manage_path(current_store)
      %li{:class => active == :dashboard ? 'active' : ''}
        = link_to t('admin.dashboard'), store_admin_dashboard_path(current_store)
      %li{:class => active == :products ? 'active' : ''}
        = link_to t('product.collection'), store_admin_products_path(current_store)
      %li{:class => active == :categories ? 'active' : ''}
        = link_to t('categories.self'), store_admin_categories_path(current_store)
      %li{:class => active == :discounts ? 'active' : ''}
        = link_to t('discounts'), store_admin_discounts_path(current_store)
    - elsif current_store.is_stocker?(current_user)
      %li.nav-header Stocker
      %li{:class => active == :products ? 'active' : ''}
        = link_to t('product.collection'), store_stock_products_path(current_store)

app/views/shared/_uber_navigation.html.haml
.span3
  %ul.nav.nav-list
    %li.nav-header Uber
    %li{:class => active == :dashboard ? 'active' : ''}
      = link_to 'Dashboard', uber_stores_path