config/routes.rb
require 'resque/server'

StoreEngine::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  resources :discounts, only: [:show]
  root to: 'stores#index'

  get "/code" => redirect("https://github.com/bradpsheehan/daughter_of_store_engine")
  put "/i18n" => "i18n#update"

  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  resources :sessions, only: [ :create ]

  get "/users/new" => "users#new", as: :signup
  resources :users, only: [ :create, :update ]

  get "/profile" => "users#show", as: :profile

  scope path: "account", as: "account" do
    get "/orders" => "orders#index", as: :orders
  end

  get "/orders/:guid" => "orders#show", as: :order

  resources :stores, only: [ :new, :create ]

  namespace :uber do
    resources :stores, only: [ :index ] do
      member do
        put :approve
        put :decline
        put :toggle_online_status
      end
    end
  end

  scope "/:store_path", as: :store do
    get "/" => "products#index", as: :home

    get "/checkout" => "checkouts#show", as: :checkout
    post "/checkout" => "checkouts#create", as: :checkout
    post "/buy_now" => "checkouts#buy_now", as: :buy_now

    resources :products, only: [ :show ]

    resource :cart, only: [ :update, :show, :destroy ] do
      member do
        put :remove_item
      end
    end

    get '/stock/products' => "admin/products#index", as: :stock_products
    get '/stock/products/:id/edit' => "admin/products#edit", as: :stock_edit_product

    namespace :admin do
      get '/' => "dashboards#manage", as: :manage

      get '/edit' => "dashboards#edit", as: :edit_store
      put '/update' => "dashboards#update", as: :update_store

      post '/role' => "roles#create", as: :create_role
      delete '/role' => "roles#destroy", as: :revoke_role

      get :dashboard, to: "orders#index", as: :dashboard

      resources :products do
        member do
          post :toggle_status
        end
      end
      resources :orders, only: [ :show, :update ]
      resources :order_items, only: [ :update, :destroy]
      resources :categories
      resources :discounts
    end
  end
end

app/models/cart.rb
class Cart
  def initialize(cart_data)
    @cart_data = cart_data
  end

  def cart_data
    @cart_data
  end

  def items
    products = Product.find(@cart_data.keys).index_by(&:id)

    @cart_data.map do |id, quantity|
      product = products[id.to_i]
      CartItem.new(product, quantity)
    end
  end

  def pretotal
    total = items.map {|item|item.total}.inject(&:+)
  end

  def remove_item(product_id)
    if product_id.present?
      @cart_data.delete(product_id)
    end
    @cart_data
  end

  def update(carts_param)
    if id = carts_param[:product_id]
      quantity = carts_param[:quantity]
      @cart_data[id] = quantity || (@cart_data[id].to_i + 1).to_s
    end
    @cart_data
  end

  def destroy
    @cart_data = {}
  end

  def count
    @cart_data.present? ? "(#{calculate_count})" : nil
  end

  def empty?
    items.empty?
  end

private
  def calculate_count
    @cart_data.values.map(&:to_i).reduce(&:+)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  class CartCalculator
    def initialize(cart,discount)
      @cart = cart
      @discount = discount
    end

    attr_reader :cart, :discount

    def sub_total
      cart.pretotal
    end

    def grand_total
      discount.apply(cart)
    end

    def savings
      sub_total - grand_total
    end

    def discount_applied?
      grand_total != sub_total
    end
  end

  def load_discount(discount_name)
    Discount.find_by_name_and_store_id(discount_name,current_store.id) || Discount.not_found
  end

  def discount_has_been_specified?
    params[:discounts]
  end

  def show
    @discount = Discount.not_found

    if discount_has_been_specified?
      @discount = load_discount(params[:discounts][:name])
      session[:discount_id] = @discount.discount_id
      flash[:notice] = @discount.message
    end

    @cart_calculator = CartCalculator.new(current_cart,@discount)

  end

  def update
    current_cart.update params[:carts]
    redirect_to(:back)
  end

  def remove_item
    current_cart.remove_item params[:product_id]
    redirect_to(:back)
  end

  def destroy
    current_cart.destroy
    redirect_to store_home_path(current_store), :notice  => "Cart cleared."
  end
end

app/views/carts/_cart_item.html.haml
- current_cart.each do |cart_item|
  .pull-right#cart-update
    = simple_form_for :carts, url: store_cart_path(current_store), method: :put do |f|
      %h5
        Quantity
      = f.hidden_field :product_id, value: cart_item.product.id
      .cart-quantity
        = f.input_field :quantity, value: cart_item.quantity, class: "input-small"
      = f.button :submit, 'Update', class:'btn'
    %br/
    %h4
      Item Total:
      -if cart_item.quantity.to_i > 1
        =number_to_currency((cart_item.unit_price) * (cart_item.quantity.to_i))
      -else
        = number_to_currency(cart_item.unit_price)
  %tr
    %td= image_tag gen_image_url(cart_item.product.id)
    %td
      %h2= link_to cart_item.title, store_product_path(current_store, cart_item.product)
      %br/
      = cart_item.product.description
      %br/
      %br/
      %br/
      .remove-item-button
        = link_to t('action.remove_item'),          |
          remove_item_store_cart_path(         |
            current_store,                     |
            product_id: cart_item.product.id), |
          confirm: t('confirm'), method: :put  |
  %hr

app/views/carts/_checkout_button.html.haml
- if current_user
  = link_to 'Checkout', store_checkout_path(current_store), class: 'btn btn-success span4'
- else
  %a.btn.btn-success.span3{"data-toggle" => "modal", :href => "#checkout_modal", :role => "button"} Checkout
  = render 'checkout_modal'

app/views/carts/_checkout_modal.html.haml
#checkout_modal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Checkout
  .modal-body
    %div{:style => "padding-right: 10px; margin-right: 10px; border-right: 1px solid #ccc; width: 225px; float:left"}
      %h4 Login
      = simple_form_for :sessions, url: sessions_path, method: 'POST' do |f|
        = f.input :email, input_html: { placeholder: t('placeholder.session.email') }
        = f.input :password
        = f.hidden_field :next_page, value: store_checkout_path(current_store)
        = f.button :submit, t('navigation.login'), class:"btn btn-custom-lighten btn-block"
      = link_to t('account.create'), signup_path(next_page: store_checkout_path(current_store))
    %div{:style => "width: 225px; float:left"}
      %h4 Checkout as Guest
      = link_to 'Continue',                 |
        store_checkout_path(current_store), |
        class: 'btn btn-block'              |
    %div{:style => "clear:both"}

app/views/carts/_discount.html.haml
= form_for :discounts, method: :get do |f|
  = f.hidden_field current_store.id
  %p= f.text_field :name, placeholder: 'Discount Code'
  %p= f.submit 'Apply'

/ This should send a GET request to a discounts_controller (or even carts controller?) where it: 1. Looks up to see if discount exists and is valid, 2. If yes - update sessions[:discount] and redirect back to cart, If no – redirect back to cart.

app/views/carts/show.html.haml
.cart-overview
  - if current_cart.empty?
    %h5= t('cart.isempty')
    = link_to t('back.home'), root_path
  - else
    %h1#cart-header Your RoboCart
    %hr
    %table.table.table-striped
      %thead
    %tbody
      = render partial: 'cart_item'
    .shopping_cart_summary
      .pull-right
        - if @cart_calculator.discount_applied?
          %h4#cart You saved #{number_to_currency(@cart_calculator.savings)}!!
          %h2#cart Total: #{number_to_currency(@cart_calculator.grand_total)}
          = render partial: 'checkout_button'
        - else
          %h2#cart Total: #{number_to_currency(@cart_calculator.grand_total)}
          %br
          = render partial: 'checkout_button'
      = button_to t('cart.empty'), store_cart_path(current_store), class: 'btn pull-left', method: :delete
      .discount-code
        = render partial: 'discount'
      %br