config/routes.rb
require 'resque/server'

StoreEngine::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  resources :discounts, only: [:show]
  root to: 'stores#index'

  get "/code" => redirect("https://github.com/bradpsheehan/daughter_of_store_engine")
  put "/i18n" => "i18n#update"

  delete "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login
  resources :sessions, only: [ :create ]

  get "/users/new" => "users#new", as: :signup
  resources :users, only: [ :create, :update ]

  get "/profile" => "users#show", as: :profile

  scope path: "account", as: "account" do
    get "/orders" => "orders#index", as: :orders
  end

  get "/orders/:guid" => "orders#show", as: :order

  resources :stores, only: [ :new, :create ]

  namespace :uber do
    resources :stores, only: [ :index ] do
      member do
        put :approve
        put :decline
        put :toggle_online_status
      end
    end
  end

  scope "/:store_path", as: :store do
    get "/" => "products#index", as: :home

    get "/checkout" => "checkouts#show", as: :checkout
    post "/checkout" => "checkouts#create", as: :checkout
    post "/buy_now" => "checkouts#buy_now", as: :buy_now

    resources :products, only: [ :show ]

    resource :cart, only: [ :update, :show, :destroy ] do
      member do
        put :remove_item
      end
    end

    get '/stock/products' => "admin/products#index", as: :stock_products
    get '/stock/products/:id/edit' => "admin/products#edit", as: :stock_edit_product

    namespace :admin do
      get '/' => "dashboards#manage", as: :manage

      get '/edit' => "dashboards#edit", as: :edit_store
      put '/update' => "dashboards#update", as: :update_store

      post '/role' => "roles#create", as: :create_role
      delete '/role' => "roles#destroy", as: :revoke_role

      get :dashboard, to: "orders#index", as: :dashboard

      resources :products do
        member do
          post :toggle_status
        end
      end
      resources :orders, only: [ :show, :update ]
      resources :order_items, only: [ :update, :destroy]
      resources :categories
      resources :discounts
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title,
                  :description,
                  :price, :status,
                  :category_ids,
                  :store_id

  has_and_belongs_to_many :categories
  belongs_to :store

  validates :title, presence: :true,
                    uniqueness: { case_sensitive: false }
  validates :description, presence: :true
  validates :status, presence: :true,
                     inclusion: { in: %w(active retired) }
  validates :price, presence: :true,
                    format: { with: /^\d+??(?:\.\d{0,2})?$/ },
                    numericality: { greater_than: 0 }
  validates :store_id, presence: true

  validates :promotion, numericality: {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }

  scope :active, lambda { where(status: 'active') }

  def self.all_cached
    Rails.cache.fetch('Product.all',expires_in: 1.day) { all }
  end

  def some_model
  end

  def self.by_category(category_id)
    if category_id.present?
      Category.find(category_id).products
    else
      scoped
    end
  end

  def promotion_savings
    (self.price * (self.promotion / 100)).to_i
  end

  def promo_price
    self.price - (self.price * (self.promotion/100))
  end

  def toggle_status
    if status == 'active'
      update_attributes(status: 'retired')
    elsif status == 'retired'
      update_attributes(status: 'active')
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_filter :require_admin
  before_filter :find_product, only: [ :edit,
                                       :update,
                                       :destroy,
                                       :toggle_status ]

  def index
    @products = current_store.products.order('created_at DESC')
                             .page(params[:page]).per(20)
  end

  def new
    @product = Product.new
  end

  def create
    promo = params[:product].delete(:promotion)
    @product = current_store.products.new(params[:product])
    if @product.save
      @product.promotion = promo
      @product.save
      redirect_to store_products_path(@role, current_store),
        :notice => "Successfully created product."
    else
      render :action => 'new', :notice  => "Product creation failed."
    end
  end

  def edit
  end

  def update
    promo = params[:product].delete(:promotion)
    if @product.update_attributes(params[:product])
      @product.promotion = promo
      @product.save
      redirect_to store_admin_products_path(current_store),
        :notice  => "Successfully updated product."
    else
      render :action => 'edit', :notice  => "Update failed."
    end
  end

  def destroy
    @product.destroy
    redirect_to store_products_path(@role, current_store),
      :notice => "Successfully destroyed product."
  end

  def toggle_status
    if @product.toggle_status
      redirect_to store_products_path(@role, current_store),
        :notice  => "Product status successfully set to '#{@product.status}'."
    else
      head 400
    end
  end

  private
  def find_product
    @product = current_store.products.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_current_store

  def index
    @current_store = Store.all_cached.find{|s| s.id == current_store.id}
    @products = @current_store.products.by_category(params[:category_id])
                             .active.page(params[:page]).per(20)
    @categories = current_store.categories
    session[:return_to] = request.fullpath
  end

  def show
    @store = current_store
    @product = @store.products.find(params[:id])
    session[:return_to] = request.fullpath
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def activate_or_retire_translation(status)
    { 'active' => t('product.retire'),
      'retired' => t('product.activate')
    }[status]
  end
end

app/views/products/_add_to_cart_button.html.haml
= simple_form_for :carts, url: store_cart_path(current_store), method: :put do |f|
  = f.hidden_field :product_id, value: product.id
  = f.button :submit, t('cart.add'), class: 'btn btn-custom-lighten'

app/views/products/_buy_now_button.html.haml
- if logged_in?
  = form_tag store_buy_now_path(current_store), id: "buyNowForm" do
    = hidden_field_tag :product_id, product.id
    %script.stripe-button.btn-custom-lighten.btn-block{"data-amount" => product.price * 100, "data-image" => gen_image_url(7), "data-key" => "pk_test_osSOH0LyEEACshdRsLjyvGSz", "data-label" => t('product.buynow'), "data-name" => t('store.name'), :src => "https://checkout.stripe.com/v2/checkout.js"}
- else
  = button_to t('product.buynow'), login_path, class: 'btn btn-primary span3', method: :get

app/views/products/_category_dropdown.html.haml
#homepage-category-dropdown.btn-group.span1
  %a.btn.btn-custom-lighten.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    = t 'categories.select'
    %span.caret
  %ul.dropdown-menu
    %li= link_to 'Show All', store_home_path(current_store)
    - if categories.present?
      - categories.each do |category|
        %li
          = link_to category.title, store_home_path(current_store, category_id: category.id), id: "category-#{category.title.gsub(/\s/,'-')}"

app/views/products/_product.html.haml
= link_to store_product_path(current_store, product) do
  .products.span3
    %p= image_tag gen_image_url(product.id)
    %h5= product.title.titleize
    %p
      = t('product.price')
      \: #{number_to_currency(product.price)}

app/views/products/_store_details.html.haml
%p
  %b Name:
  = @store.name
%p
  %b Path:
  = @store.path
%p
  %b Description:
  = @store.description

app/views/products/index.html.haml
- if current_store.pending?
  %p#notice= "Not Found: This store is pending approval."
  = render partial: 'store_details'
- else
  .product-index
    %section.row
      = render partial: 'category_dropdown', |
        locals: { categories: @categories }  |
    %br/
    #product_listing.row-fluid
      = render @products
    .pagination
      = paginate @products

app/views/products/show.html.haml
.row
  .prod_detail_img.span6
    = image_tag gen_image_url(@product.id)
  .prod_detail_text.span5
    %h2
      - t('product.title')
      = @product.title
    %hr/
    %p
      - t('product.description')
      = @product.description
    #product-categories
      %b
        = t('categories.self')
        \:
      - @product.categories.each do |category|

        %span.label= link_to category.title, store_home_path(current_store, category_id: category.id), {:style=>'color:#DCDCDC;', :class => "strokeme"} 
    %br/
    -if @product.promotion > 0
      %h4(id="strike-through")
        = t('product.price')
        \: #{number_to_currency(@product.price)}
        %br
      %h3
        = t('product.promo_price')
        \: #{number_to_currency(@product.promo_price)}
      %h5
        = ("You save #{@product.promotion.to_i}% or $#{@product.promotion_savings}")
    -else
      %h4
        = t('product.price')
        \: #{number_to_currency(@product.price)}
    %br/
    - if @product.status == 'active'
      = render partial: 'add_to_cart_button', locals: {product: @product}
      = render partial: 'buy_now_button', locals: {product: @product}
    - else
      %p Product is retired!